### ISSUE TITLE
CMS removes escape characters by changing from rich text to markdown and back

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#141]
Hi,
I have the following issue when I copy this text into markdown:
**Die Syntax dafür ist:
{minimal number, maximal number}

{0,1} minimal 0 maximal 1 (entspricht ?), z.B.

- \[word=".{10}"] genau 10 Wiederholungen von "." – also alle Wörter oder Zahlen mit Länge 10**

I need to escape {, [,], and}, so I add "\" before them. Once done, the rendering of the preview is fine and I switch back to rich text. Now, as soon as I add some changes (for example, chance an element to bold text in rich text just before this piece), the rendering doesn't work anymore. When I now go back to markdown, I find that all the escape characters "\" are gone again. 
Any idea what causes this glitch? I would have liked to  - finally - complete the AMC post...

Thanks
best wishes
Elisabeth

**Comment by stefanprobst** [comment]
this is about https://github.com/acdh-oeaw/howto/blob/a6de65e8ad0ab8718e4a24c76261552a1ebc3336/content/posts/corpus-query-language-im-austrian-media-corpus/index.mdx?plain=1#L471-L479 correct?

can you try wrapping in inline code blocks, i.e. wrap in backticks like this:

```
- `[word=".{10}"]` genau 10 Wiederholungen von "." – also alle Wörter oder Zahlen mit Länge 10
```
