### ISSUE TITLE
Cannot log in to CMS

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/howto#158]
Trying to open:
https://howto.acdh.oeaw.ac.at/cms#

I am presented with: 

![image](https://user-images.githubusercontent.com/8236186/220097418-2f88e648-cc48-42d7-91d9-0f213a8faa88.png)

Just clicking on "Login with GitHub" immediatly returns: 

```json
{
"message": "No GitHub ID provided."
}
```

**Comment by stefanprobst** [comment]
environment variables + secrets were not migrated when the service was moved from acdh cluster to cluster2.

**Comment by stefanprobst** [comment]
should be fixed now.
