### ISSUE TITLE
Underscore escape and representation

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#170]
In the AMC branch (first CQL / regex paragraph) contains a descriptive list of characters that can be used as wildcards etc in regex. One of them is the underscore. It is not rendered (seems to cause problems too) but can't be marked as a non-special character by single quotations (=in line code), exclamation mark, backslash, percentage. Not sure what else to try

**Comment by stefanprobst** [comment]
this should work:

```
characters: `_`
```

inline code is marked with backticks, not single quotes. the underscore is a formatting character in markdown for italics.

**Comment by ekoenigshofer** [comment]
It does work indeed. True, I mixed them up.
I'll put the other regex in inline code too, for the sake of uniform appearance in the text
