### ISSUE TITLE
Constantly trying to render...

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#172]
Currently, the preview in the CMS is constantly trying to render (on Windows), without any output; I tried on unfinished texts (AMC) and on text where I know that there is no rendering issue or even starting a new post; rendering does not work.

Any ideas?

**Comment by stefanprobst** [comment]
may be fixed by https://github.com/acdh-oeaw/howto/commit/be26b0a3afac59514bcf87e552764390aadba69f
