### ISSUE TITLE
Corpus Query Language im Austrian Media Corpus docker image deploy

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#173]
The following problem occurs when publishing the "Corpus Query Language im Austrian Media Corpus" post.
"Build and deploy a Docker image / build-deploy " - all jobs have failed.

Not sure why this happens, the post appears a published and in the content list.

**Comment by stefanprobst** [comment]
according to logs:

![Screenshot_20230502_192720](https://user-images.githubusercontent.com/20753323/235740034-7898d1a9-bc0c-483f-bc80-9ad6b687e872.png)

**Comment by stefanprobst** [comment]
i guess this has been fixed? thanks!
