### ISSUE TITLE
Failed deploy? node.js 12 deprecated information; 

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#181]
In commit b961454 I get the following:
 Automatically generated. Merged on Netlify CMS

Force merge of:
* "content/posts/lesson-1-make-a-plan-then-don’t-stick-to-it/images/sk-banner.png"
* "content/posts/lesson-1-make-a-plan-then-don’t-stick-to-it/images/walpurgisnacht_az_19332005_fahnenverbot_complete.png"
* "content/posts/lesson-1-make-a-plan-then-don’t-stick-to-it/index.mdx"
* "content/posts/lesson-2-meet-the-data-examples-of-data-perspectivity/images/sk-banner-large.jpeg"
* "content/posts/lesson-2-meet-the-data-examples-of-data-perspectivity/images/sk-banner.png"
* "content/posts/lesson-2-meet-the-data-examples-of-data-perspectivity/images/sk-small.png"
* "content/posts/lesson-2-meet-the-data-examples-of-data-perspectivity/images/sk-square.png"
* "content/posts/lesson-2-meet-the-data-examples-of-data-perspectivity/images/walpurgisnacht_az_19332005_fahnenverbot_complete.png"
* * "content/posts/lesson-2-meet-the-data-examples-of-data-perspectivity/index.mdx"
* "src/navigation/navigation.config.ts"
* "src/views/ResourcesList.tsx"

"Lesson 2" also shows up in the content/posts list. 
However, I get a deployment fail: https://github.com/acdh-oeaw/howto/actions/runs/4958523986; stating that the docker-image does not deploy:
ERROR: failed to solve: process "/bin/sh -c yarn run build" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c yarn run build" did not complete successfully: exit code: 1

I'll try to rerun (last time we had a picture with a symbol it didn't like but I don't think that is the case now)

**Comment by ekoenigshofer** [comment]
Tried rerun, not working

**Comment by ekoenigshofer** [comment]
edit: Lesson 2 is also visible on the cms (as part of the content), but it does not render on the website

**Comment by stefanprobst** [comment]
thanks, will take a look

**Comment by ekoenigshofer** [comment]
Maybe I found it. There were 3 posts now, 2 of them correct and one an odd mix, that might have caused confusion. I took the odd one back to draft stage. maybe it will do what it should now

**Comment by ekoenigshofer** [comment]
no, no deployment of "Lesson 2", although it sits in contents/posts
