### ISSUE TITLE
CMS removes content from Tabs structures under certain circumstances

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/howto#204]
The CMS UI for Tabs hows 0 tabs sometimes althought there are tabs and they contain content.

Steps to reproduce:

I am not 100% sure how to trigger this.
* I switched beween Markdown and Rich Text to upload Images and then put them within a Tabs construct
* The Tabs I edited were not the ones that got deleted but some other in different parts of the document.

See these commits
* 1bad2bcefde99, 7dac495c63
* 7dac495c63

**Comment by stefanprobst** [comment]
fixed in new version.
