### ISSUE TITLE
URL encoding issue in linked image names

### ISSUE THREAD

**Issue by maria-wie** [acdh-oeaw/howto#222]
On DYLEN page we have two image files with umlauts in the name and when the server tries to load them it uses URL encoded versions of the name and doesn't find the files.

The links in question are here:
https://github.com/acdh-oeaw/howto/blob/main/content/posts/dylen/index.mdx#L136
https://github.com/acdh-oeaw/howto/blob/main/content/posts/dylen/index.mdx#L142

Shall I rename the files or do we want to address this in a different way?

**Comment by stefanprobst** [comment]
fixed in new version.
