### ISSUE TITLE
XML quiz code editor does not preserve whitespace for line indents

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#28]
It would be helpful if the code editor had some kind of code and syntax highlighting, like VS Code or Atom have. This way, it would be easier for users to see if they apply their knowledge correctly.
No real preference as to what colour scheme etc should there.

It doesn't disrupt functionality, but it would be nice to have

**Comment by stefanprobst** [comment]
is this about the richtext editor widget for adding code blocks, i.e. this one?

![Screenshot_20210721_124900](https://user-images.githubusercontent.com/20753323/126477028-f5ade528-db90-4214-8948-1b88448097ac.png)

**Comment by ekoenigshofer** [comment]
yes, it is. I've seen now that it does the colouring for various xml elements; this issue might be resolved? Need to ask @fwiencek if that is sufficient. I've popped one entry into the "in review" section, you can see an example in "Übung 2a", to see the difference between editing and user mode.

**Comment by stefanprobst** [comment]
so, for regular code blocks embedded in the text, you can select the code language via the "cog wheel" settings button in the top right corner, which should give you syntax highlighting.

for the xml quiz, the editor widget is preconfigured to xml, so you should get syntax highlighting for xml elements.

what's currently not working it seems is that we lose the indents (note to self: which probably has to do with whitespace handling in attributes)

**Comment by stefanprobst** [comment]
![Screenshot_20210721_132301](https://user-images.githubusercontent.com/20753323/126481098-6eec6780-2bac-479b-8b62-0dab1ec5d7ff.png)

becomes

![Screenshot_20210721_132331](https://user-images.githubusercontent.com/20753323/126481178-c1b0ab35-8ef4-46c2-bf0e-c3fdab9b447f.png)

**Comment by stefanprobst** [comment]
indentation should now be preserved.

closing this, but feel free to reopen if there's other issues with the xml editor.
