### ISSUE TITLE
highlight correct and wrong answers in multiple choice

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#29]
Enable users to see if the answers they selected were right or wrong, not just validating that they have given an overall correct answer (e.g. if they need to select 3 options to get it right, and they only find 2, show that these two are correct by highlighting them).
See for an example:
https://oeawacat.sharepoint.com/:w:/r/sites/ACDH-CH_p_DiTAH_DigitaleTransformationsterreichischeGeistesw/Shared%20Documents/General/Training/Feature%20Requests%20%26%20Bugreports%20HowTo%20-%202021-07-14.docx?d=w892c42a7ec5848b48315cecf3667ef57&csf=1&web=1&e=BYoa5a

**Comment by stefanprobst** [comment]
should this be the default behavior, or triggered by e.g. pressing a "Show hint" button, which could highlight correct/incorrect answers and optionally show a message?

**Comment by ekoenigshofer** [comment]
I'd say triggered - could it work with just one "validate"/"check" button? 
i.e. once i've ticked my answers, I click "check" and then I see a "sorry, not all is correct" message and at the same time it highlights the correct ones? and then I do it again (untick the wrong, choose another) and I can see that all my choices are correct.

Obviously, there is the issue that I do not know then if I missed an answer that is correct and needed to get the "check" as a totally correct answer. We could always state how many correct answers there are. But not sure if this gives away too much / too many hints. We could also say "hint" and then say "there are 3 (or whatever) correct answers".

**Comment by stefanprobst** [comment]
what's already possible is to add custom success and failure messages which show after pressing validate, e.g. a user clicks "Validate" and the widget shows either the success message in case the answer is correct, or a failure message in case something is wrong. 

personally i think it makes sense to *not* mix "This is so wrong!" messages with "Here's a helpful tip".

also to think about: highlights mostly make sense for multiple choice but might be less applicable for other types of quiz cards
