### ISSUE TITLE
represent in-line code without `...` 

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#31]
currently, the quotation marks are still present; shall we put them in differently, so that this doesn't show?

**Comment by stefanprobst** [comment]
could you clarify which quotations marks this is about?

this is how inline code renders for me:

![Screenshot_20210721_124538](https://user-images.githubusercontent.com/20753323/126476629-64ab2783-421b-479d-a2c2-e960632d639e.png)

**Comment by ekoenigshofer** [comment]
I think it this is resolved and can be closed.
I realised it had stopped show in the regular rich text editor. Rich text seems to work now in the quiz sections, too. In any case, what is saw before is resolved now when I check in the "TEI Body" entry.
