### ISSUE TITLE
add i18n for tag description and author description

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/howto#32]
if we decide to limit language support to de/en, we could easily translate tag description and author description (and show the one matching the currently selected UI language)

**Comment by ekoenigshofer** [comment]
On that: there was a suggestion (I think in body) to use "Überprüfen" for the validation button in the German version. Is everybody happy to use that? Open to alternatives!

**Comment by stefanprobst** [comment]
> use "Überprüfen" for the validation button in the German version

this should already be the case - the cms preview currently defaults to english though, so it will only be visible once published
