### ISSUE TITLE
Comment function for editors and reviewers

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#55]
We should consider having a rich text function to add  comments which are not displayed but there as notes for the editors when the author reviews the material prior to publishing.
In addtion, users testing the material should be able to comment

- Use github comments? This could work because each material lives on its own branch
- Publish drafts as specific URL to comment (as vercel and other hosting platforms do, e.g.: https://github.com/stefanprobst/campus/pull/25)

**Comment by stefanprobst** [comment]
- i would prefer to just use GitHub for comments and reviews
- in case somebody realllly wants to leave hidden comments inline, they can always wrap then with `<div hidden>My secret comment</div>`
