### ISSUE TITLE
Dead Link to GND in "Prosopographic Modelling - Individuals"

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/howto#61]
[This link](https://github.com/acdh-oeaw/howto/blob/a44f13c98054632ab0ff4182a87b27f3ef22d4b2/content/posts/prosopographic-modelling-individuals/index.mdx?plain=1#L165) is dead: https://d-nb.info/gnd

Is the GND living at https://gnd.network now?

**Comment by sennierer** [comment]
I think that should be changed to https://d-nb.info/standards/elementset/gnd

**Comment by stefanprobst** [comment]
thanks, fixed.
