### ISSUE TITLE
WebVOWL depricated/ Alternative, LOD Playground SPARQL queries

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#66]
WebVOWL has been depricated: alternative is [open source version](http://vowl.visualdataweb.org/webvowl.html) - Vera looks into what version to use and where data should be stored (question for Matej?); seems easy to create.

LOD Playground SPARQL queries: who has the file with queries? Can't be found on playground anymore. (potentially Gregor has them)

--> need both for running student user test at Krems

**Comment by stefanprobst** [comment]
what's the status here?
